DROP TABLE IF EXISTS stat CASCADE;

CREATE TABLE IF NOT EXISTS stat (
id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
app VARCHAR(128)                                    NOT NULL,
uri VARCHAR(128)                                    NOT NULL,
ip VARCHAR(16)                                      NOT NULL,
created TIMESTAMP WITHOUT TIME ZONE NOT NULL
);